#!/bin/sh

romName="fourswords"

echo =========================================
echo                 Compressing
echo =========================================
cp assets/misc/$romName.png .
zip assets/misc/data/$romName.zip $romName.gba $romName.png
rm $romName.png
rm $romName.gba
mv assets/misc/data/$romName.zip /var/www/website/store/items/gba/homebrew