#!/bin/sh

echo =========================================
echo                 Compiling Textures
echo =========================================



#=======================================================================
#
#	tileMaps, 1024x1024@4, 
#	+ palette 256 entries, not compressed
#	+ 16384 tiles lz77 compressed
#	Total size: 512 + 115164 = 115676
#
#	Time-stamp: 2022-12-28, 22:44:39
#	Exported by Cearn's GBA Image Transmogrifier, v0.9.2
#	( http://www.coranac.com/projects/#grit )
#
#=======================================================================


mkdir assets/gfx/resources

echo compiling sprites...
for sprite in $(cat assets/misc/data/lists/tex.spr)
do /opt/devkitpro/tools/bin/grit assets/gfx/sprites/$sprite.png -ff assets/misc/data/grit/$sprite.grit -o assets/gfx/resources/spriteMaps
done

echo compiling tilesets... 
for tileset in $(cat assets/misc/data/lists/tex.til)
do /opt/devkitpro/tools/bin/grit assets/gfx/tilesets/$tileset.png -ff assets/misc/data/grit/$tileset.grit -o assets/gfx/resources/tileSets
done

echo compiling tilemaps... 
for tilemap in $(cat assets/misc/data/lists/tex.map)
do /opt/devkitpro/tools/bin/grit assets/gfx/tilemaps/$tilemap.png -ff assets/misc/data/grit/$tilemap.grit -o assets/gfx/resources/tileMaps
done

for source in $(ls assets/gfx/resources | grep .c)
do mv assets/gfx/resources/$source source/resources
done

for header in $(ls assets/gfx/resources | grep .h)
do mv assets/gfx/resources/$header assets/include/resources
done

rm assets/gfx/resources -r

